version: "3.8"

services:

  server:
    depends_on:
      - mongodb
      - nginx
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      NODE_ENV: production
      DB_HOST: mongo://localhost:27017
      DB_PORT: 27017
      DB_USER: "reon"
      DB_PASSWORD: "reon"
      DB_NAME: "nps"
    ports:
      - 3000:3000
    networks:
      - local_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "reon"
      MONGO_INITDB_DATABASE: "nps"
    ports:
      - 27017:27017
    volumes:
      - ../db/nps:/data/db
    networks:
      - local_network

  nginx:
    image: nginx:stable-alpine3.17
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
